package enemeez.simplefarming.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class HungerConfig {

	public static ForgeConfigSpec.IntValue berry;
	public static ForgeConfigSpec.IntValue fruit;
	public static ForgeConfigSpec.IntValue gourd_slice;
	public static ForgeConfigSpec.IntValue cassava;
	public static ForgeConfigSpec.IntValue corn;
	public static ForgeConfigSpec.IntValue cucumber;
	public static ForgeConfigSpec.IntValue eggplant;
	public static ForgeConfigSpec.IntValue ginger;
	public static ForgeConfigSpec.IntValue onion;
	public static ForgeConfigSpec.IntValue peanut;
	public static ForgeConfigSpec.IntValue pepper;
	public static ForgeConfigSpec.IntValue pea_pod;
	public static ForgeConfigSpec.IntValue radish;
	public static ForgeConfigSpec.IntValue soybean;
	public static ForgeConfigSpec.IntValue sorghum;
	public static ForgeConfigSpec.IntValue salad_greens;
	public static ForgeConfigSpec.IntValue tomato;
	public static ForgeConfigSpec.IntValue turnip;
	public static ForgeConfigSpec.IntValue sweet_potato;
	public static ForgeConfigSpec.IntValue seeds;
	public static ForgeConfigSpec.IntValue zucchini;
	public static ForgeConfigSpec.IntValue broccoli;
	public static ForgeConfigSpec.IntValue olives;
	public static ForgeConfigSpec.IntValue golden_habanero;
	public static ForgeConfigSpec.IntValue berry_pie;
	public static ForgeConfigSpec.IntValue fruit_pie;
	public static ForgeConfigSpec.IntValue baked_sweet_potato;
	public static ForgeConfigSpec.IntValue banana_bread;
	public static ForgeConfigSpec.IntValue blt;
	public static ForgeConfigSpec.IntValue caesar_salad;
	public static ForgeConfigSpec.IntValue cassava_cake;
	public static ForgeConfigSpec.IntValue cheese_slice;
	public static ForgeConfigSpec.IntValue cheese_burger;
	public static ForgeConfigSpec.IntValue chicken_parmesan;
	public static ForgeConfigSpec.IntValue chili;
	public static ForgeConfigSpec.IntValue chocolate;
	public static ForgeConfigSpec.IntValue cooked_bacon;
	public static ForgeConfigSpec.IntValue cooked_chicken_wings;
	public static ForgeConfigSpec.IntValue cooked_egg;
	public static ForgeConfigSpec.IntValue cooked_sausage;
	public static ForgeConfigSpec.IntValue corn_salad;
	public static ForgeConfigSpec.IntValue corn_bread;
	public static ForgeConfigSpec.IntValue cucumber_soup;
	public static ForgeConfigSpec.IntValue egg_sandwich;
	public static ForgeConfigSpec.IntValue eggplant_parmesan;
	public static ForgeConfigSpec.IntValue fish_fillet;
	public static ForgeConfigSpec.IntValue fish_sandwich;
	public static ForgeConfigSpec.IntValue fried_calamari;
	public static ForgeConfigSpec.IntValue fruit_salad;
	public static ForgeConfigSpec.IntValue hamburger;
	public static ForgeConfigSpec.IntValue hotdog;
	public static ForgeConfigSpec.IntValue jaffa_cake;
	public static ForgeConfigSpec.IntValue lasagna;
	public static ForgeConfigSpec.IntValue mac_and_cheese;
	public static ForgeConfigSpec.IntValue oatmeal;
	public static ForgeConfigSpec.IntValue onion_soup;
	public static ForgeConfigSpec.IntValue pancakes;
	public static ForgeConfigSpec.IntValue pasta;
	public static ForgeConfigSpec.IntValue pickle;
	public static ForgeConfigSpec.IntValue pickled_beetroot;
	public static ForgeConfigSpec.IntValue pizza;
	public static ForgeConfigSpec.IntValue popcorn;
	public static ForgeConfigSpec.IntValue pulled_pork_sandwich;
	public static ForgeConfigSpec.IntValue radish_soup;
	public static ForgeConfigSpec.IntValue raw_bacon;
	public static ForgeConfigSpec.IntValue raw_calamari;
	public static ForgeConfigSpec.IntValue raw_chicken_wings;
	public static ForgeConfigSpec.IntValue raw_sausage;
	public static ForgeConfigSpec.IntValue rice_bowl;
	public static ForgeConfigSpec.IntValue salad;
	public static ForgeConfigSpec.IntValue sandwich;
	public static ForgeConfigSpec.IntValue spaghetti;
	public static ForgeConfigSpec.IntValue spinach_mushroom_quiche;
	public static ForgeConfigSpec.IntValue squash_casserole;
	public static ForgeConfigSpec.IntValue sushi;
	public static ForgeConfigSpec.IntValue tofu;
	public static ForgeConfigSpec.IntValue tomato_soup;
	public static ForgeConfigSpec.IntValue vegetable_medley;
	public static ForgeConfigSpec.IntValue veggie_burger;
	public static ForgeConfigSpec.IntValue tofu_scramble;
	public static ForgeConfigSpec.IntValue raisins;
	public static ForgeConfigSpec.IntValue chicken_noodle_soup;
	public static ForgeConfigSpec.IntValue quinoa_salad;
	public static ForgeConfigSpec.IntValue squash_soup;
	public static ForgeConfigSpec.IntValue spinach_quinoa_quiche;
	public static ForgeConfigSpec.IntValue beef_curry;
	public static ForgeConfigSpec.IntValue chicken_curry;
	public static ForgeConfigSpec.IntValue mutton_curry;
	public static ForgeConfigSpec.IntValue pork_curry;
	public static ForgeConfigSpec.IntValue vegetable_curry;
	public static ForgeConfigSpec.IntValue peanut_butter_pie;
	public static ForgeConfigSpec.IntValue sorghum_bread;
	public static ForgeConfigSpec.IntValue sorghum_porridge;
	public static ForgeConfigSpec.IntValue italian_beef;
	public static ForgeConfigSpec.IntValue peanut_butter_cookie;
	public static ForgeConfigSpec.IntValue pbj;
	public static ForgeConfigSpec.IntValue trail_mix;
	public static ForgeConfigSpec.IntValue carrot_soup;
	public static ForgeConfigSpec.IntValue pumpkin_soup;
	public static ForgeConfigSpec.IntValue pea_soup;
	public static ForgeConfigSpec.IntValue fried_rice;
	public static ForgeConfigSpec.IntValue sweet_potato_quinoa_cakes;
	public static ForgeConfigSpec.IntValue sausage_barley;
	public static ForgeConfigSpec.IntValue mushroom_barley;
	public static ForgeConfigSpec.IntValue beef_and_broccoli;
	public static ForgeConfigSpec.IntValue broccoli_cheese_soup;
	public static ForgeConfigSpec.IntValue stuffed_corn_zucchini;
	public static ForgeConfigSpec.IntValue zucchini_bread;
	public static ForgeConfigSpec.IntValue olive_tomato_salad;
	public static ForgeConfigSpec.IntValue candy;
	public static ForgeConfigSpec.IntValue borscht;
	public static ForgeConfigSpec.IntValue squid_ink_pasta;
	public static ForgeConfigSpec.IntValue fish_and_chips;
	public static ForgeConfigSpec.IntValue marshmallow;
	public static ForgeConfigSpec.IntValue pad_thai;
	public static ForgeConfigSpec.IntValue potato_knish;
	public static ForgeConfigSpec.IntValue chicory_gratin;
	public static ForgeConfigSpec.IntValue turnip_beetroot_gratin;
	public static ForgeConfigSpec.IntValue ice_cream_sundae;
	public static ForgeConfigSpec.IntValue candy_cane;

	public static void init(ForgeConfigSpec.Builder config) {
		
		berry = config.defineInRange("berry (default = 2)", 2, 0, Integer.MAX_VALUE);
		fruit = config.defineInRange("fruit (default = 4)", 4, 0, Integer.MAX_VALUE);
		gourd_slice = config.defineInRange("gourd_slice (default = 2)", 2, 0, Integer.MAX_VALUE);
		cassava = config.defineInRange("cassava (default = 3)", 3, 0, Integer.MAX_VALUE);
		corn = config.defineInRange("corn (default = 6)", 6, 0, Integer.MAX_VALUE);
		cucumber = config.defineInRange("cucumber (default = 3)", 3, 0, Integer.MAX_VALUE);
		eggplant = config.defineInRange("eggplant (default = 3)", 3, 0, Integer.MAX_VALUE);
		ginger = config.defineInRange("ginger (default = 2)", 2, 0, Integer.MAX_VALUE);
		onion = config.defineInRange("onion (default = 3)", 3, 0, Integer.MAX_VALUE);
		peanut = config.defineInRange("peanut (default = 1)", 1, 0, Integer.MAX_VALUE);
		pepper = config.defineInRange("pepper (default = 2)", 2, 0, Integer.MAX_VALUE);
		pea_pod = config.defineInRange("pea_pod (default = 2)", 2, 0, Integer.MAX_VALUE);
		radish = config.defineInRange("radish (default = 1)", 1, 0, Integer.MAX_VALUE);
		soybean = config.defineInRange("soybean (default = 2)", 2, 0, Integer.MAX_VALUE);
		sorghum = config.defineInRange("sorghum (default = 4)", 4, 0, Integer.MAX_VALUE);
		salad_greens = config.defineInRange("salad_greens (default = 2)", 2, 0, Integer.MAX_VALUE);
		tomato = config.defineInRange("tomato (default = 3)", 3, 0, Integer.MAX_VALUE);
		turnip = config.defineInRange("turnip (default = 2)", 2, 0, Integer.MAX_VALUE);
		sweet_potato = config.defineInRange("sweet_potato (default = 2)", 2, 0, Integer.MAX_VALUE);
		seeds = config.defineInRange("seeds (default = 1)", 1, 0, Integer.MAX_VALUE);
		zucchini = config.defineInRange("zucchini (default = 3)", 3, 0, Integer.MAX_VALUE);
		broccoli = config.defineInRange("broccoli (default = 3)", 3, 0, Integer.MAX_VALUE);
		olives = config.defineInRange("olives (default = 2)", 2, 0, Integer.MAX_VALUE);
		golden_habanero = config.defineInRange("golden_habanero (default = 2)", 2, 0, Integer.MAX_VALUE);
		berry_pie = config.defineInRange("berry_pie (default = 4)", 4, 0, Integer.MAX_VALUE);
		fruit_pie = config.defineInRange("fruit_pie (default = 6)", 6, 0, Integer.MAX_VALUE);
		baked_sweet_potato = config.defineInRange("baked_sweet_potato (default = 6)", 6, 0, Integer.MAX_VALUE);
		banana_bread = config.defineInRange("banana_bread (default = 7)", 7, 0, Integer.MAX_VALUE);
		blt = config.defineInRange("blt (default = 14)", 14, 0, Integer.MAX_VALUE);
		caesar_salad = config.defineInRange("caesar_salad (default = 11)", 11, 0, Integer.MAX_VALUE);
		cassava_cake = config.defineInRange("cassava_cake (default = 5)", 5, 0, Integer.MAX_VALUE);
		cheese_slice = config.defineInRange("cheese_slice (default = 3)", 3, 0, Integer.MAX_VALUE);
		cheese_burger = config.defineInRange("cheese_burger (default = 21)", 21, 0, Integer.MAX_VALUE);
		chicken_parmesan = config.defineInRange("chicken_parmesan (default = 15)", 15, 0, Integer.MAX_VALUE);
		chili = config.defineInRange("chili (default = 13)", 13, 0, Integer.MAX_VALUE);
		chocolate = config.defineInRange("chocolate (default = 3)", 3, 0, Integer.MAX_VALUE);
		cooked_bacon = config.defineInRange("cooked_bacon (default = 4)", 4, 0, Integer.MAX_VALUE);
		cooked_chicken_wings = config.defineInRange("cooked_chicken_wings (default = 3)", 3, 0, Integer.MAX_VALUE);
		cooked_egg = config.defineInRange("cooked_egg (default = 5)", 5, 0, Integer.MAX_VALUE);
		cooked_sausage = config.defineInRange("cooked_sausage (default = 4)", 4, 0, Integer.MAX_VALUE);
		corn_salad = config.defineInRange("corn_salad (default = 9)", 9, 0, Integer.MAX_VALUE);
		corn_bread = config.defineInRange("corn_bread (default = 7)", 7, 0, Integer.MAX_VALUE);
		cucumber_soup = config.defineInRange("cucumber_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		egg_sandwich = config.defineInRange("egg_sandwich (default = 14)", 14, 0, Integer.MAX_VALUE);
		eggplant_parmesan = config.defineInRange("eggplant_parmesan (default = 16)", 16, 0, Integer.MAX_VALUE);
		fish_fillet = config.defineInRange("fish_fillet (default = 8)", 8, 0, Integer.MAX_VALUE);
		fish_sandwich = config.defineInRange("fish_sandwich (default = 15)", 15, 0, Integer.MAX_VALUE);
		fried_calamari = config.defineInRange("fried_calamari (default = 5)", 5, 0, Integer.MAX_VALUE);
		fruit_salad = config.defineInRange("fruit_salad (default = 8)", 8, 0, Integer.MAX_VALUE);
		hamburger = config.defineInRange("hamburger (default = 18)", 18, 0, Integer.MAX_VALUE);
		hotdog = config.defineInRange("hotdog (default = 9)", 9, 0, Integer.MAX_VALUE);
		jaffa_cake = config.defineInRange("jaffa_cake (default = 8)", 8, 0, Integer.MAX_VALUE);
		lasagna = config.defineInRange("lasagna (default = 24)", 24, 0, Integer.MAX_VALUE);
		mac_and_cheese = config.defineInRange("mac_and_cheese (default = 10)", 10, 0, Integer.MAX_VALUE);
		oatmeal = config.defineInRange("oatmeal (default = 3)", 3, 0, Integer.MAX_VALUE);
		onion_soup = config.defineInRange("onion_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		pancakes = config.defineInRange("pancakes (default = 4)", 4, 0, Integer.MAX_VALUE);
		pasta = config.defineInRange("pasta (default = 10)", 10, 0, Integer.MAX_VALUE);
		pickle = config.defineInRange("pickle (default = 5)", 5, 0, Integer.MAX_VALUE);
		pickled_beetroot = config.defineInRange("pickled_beetroot (default = 3)", 3, 0, Integer.MAX_VALUE);
		pizza = config.defineInRange("pizza (default = 10)", 10, 0, Integer.MAX_VALUE);
		popcorn = config.defineInRange("popcorn (default = 1)", 1, 0, Integer.MAX_VALUE);
		pulled_pork_sandwich = config.defineInRange("pulled_pork_sandwich (default = 18)", 18, 0, Integer.MAX_VALUE);
		radish_soup = config.defineInRange("radish_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		raw_bacon = config.defineInRange("raw_bacon (default = 2)", 2, 0, Integer.MAX_VALUE);
		raw_calamari = config.defineInRange("raw_calamari (default = 2)", 2, 0, Integer.MAX_VALUE);
		raw_chicken_wings = config.defineInRange("raw_chicken_wings (default = 1)", 1, 0, Integer.MAX_VALUE);
		raw_sausage = config.defineInRange("raw_sausage (default = 2)", 2, 0, Integer.MAX_VALUE);
		rice_bowl = config.defineInRange("rice_bowl (default = 3)", 3, 0, Integer.MAX_VALUE);
		salad = config.defineInRange("salad (default = 12)", 12, 0, Integer.MAX_VALUE);
		sandwich = config.defineInRange("sandwich (default = 16)", 16, 0, Integer.MAX_VALUE);
		spaghetti = config.defineInRange("spaghetti (default = 10)", 10, 0, Integer.MAX_VALUE);
		spinach_mushroom_quiche = config.defineInRange("spinach_mushroom_quiche (default = 10)", 10, 0, Integer.MAX_VALUE);
		squash_casserole = config.defineInRange("squash_casserole (default = 9)", 9, 0, Integer.MAX_VALUE);
		sushi = config.defineInRange("sushi (default = 8)", 8, 0, Integer.MAX_VALUE);
		tofu = config.defineInRange("tofu (default = 6)", 6, 0, Integer.MAX_VALUE);
		tomato_soup = config.defineInRange("tomato_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		vegetable_medley = config.defineInRange("vegetable_medley (default = 6)", 6, 0, Integer.MAX_VALUE);
		veggie_burger = config.defineInRange("veggie_burger (default = 16)", 16, 0, Integer.MAX_VALUE);
		tofu_scramble = config.defineInRange("tofu_scramble (default = 12)", 12, 0, Integer.MAX_VALUE);
		raisins = config.defineInRange("raisins (default = 8)", 8, 0, Integer.MAX_VALUE);
		chicken_noodle_soup = config.defineInRange("chicken_noodle_soup (default = 13)", 13, 0, Integer.MAX_VALUE);
		quinoa_salad = config.defineInRange("quinoa_salad (default = 5)", 5, 0, Integer.MAX_VALUE);
		squash_soup = config.defineInRange("squash_soup (default = 12)", 12, 0, Integer.MAX_VALUE);
		spinach_quinoa_quiche = config.defineInRange("spinach_quinoa_quiche (default = 10)", 10, 0, Integer.MAX_VALUE);
		beef_curry = config.defineInRange("beef_curry (default = 18)", 18, 0, Integer.MAX_VALUE);
		chicken_curry = config.defineInRange("chicken_curry (default = 16)", 16, 0, Integer.MAX_VALUE);
		mutton_curry = config.defineInRange("mutton_curry (default = 16)", 16, 0, Integer.MAX_VALUE);
		pork_curry = config.defineInRange("pork_curry (default = 18)", 18, 0, Integer.MAX_VALUE);
		vegetable_curry = config.defineInRange("vegetable_curry (default = 12)", 12, 0, Integer.MAX_VALUE);
		peanut_butter_pie = config.defineInRange("peanut_butter_pie (default = 3)", 3, 0, Integer.MAX_VALUE);
		sorghum_bread = config.defineInRange("sorghum_bread (default = 7)", 7, 0, Integer.MAX_VALUE);
		sorghum_porridge = config.defineInRange("sorghum_porridge (default = 8)", 8, 0, Integer.MAX_VALUE);
		italian_beef = config.defineInRange("italian_beef (default = 18)", 18, 0, Integer.MAX_VALUE);
		peanut_butter_cookie = config.defineInRange("peanut_butter_cookie (default = 4)", 4, 0, Integer.MAX_VALUE);
		pbj = config.defineInRange("pbj (default = 8)", 8, 0, Integer.MAX_VALUE);
		trail_mix = config.defineInRange("trail_mix (default = 12)", 12, 0, Integer.MAX_VALUE);
		carrot_soup = config.defineInRange("carrot_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		pumpkin_soup = config.defineInRange("pumpkin_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		pea_soup = config.defineInRange("pea_soup (default = 4)", 4, 0, Integer.MAX_VALUE);
		fried_rice = config.defineInRange("fried_rice (default = 9)", 9, 0, Integer.MAX_VALUE);
		sweet_potato_quinoa_cakes = config.defineInRange("sweet_potato_quinoa_cakes (default = 6)", 6, 0, Integer.MAX_VALUE);
		sausage_barley = config.defineInRange("sausage_barley (default = 10)", 10, 0, Integer.MAX_VALUE);
		mushroom_barley = config.defineInRange("mushroom_barley (default = 4)", 4, 0, Integer.MAX_VALUE);
		beef_and_broccoli = config.defineInRange("beef_and_broccoli (default = 14)", 14, 0, Integer.MAX_VALUE);
		broccoli_cheese_soup = config.defineInRange("broccoli_cheese_soup (default = 6)", 6, 0, Integer.MAX_VALUE);
		stuffed_corn_zucchini = config.defineInRange("stuffed_corn_zucchini (default = 14)", 14, 0, Integer.MAX_VALUE);
		zucchini_bread = config.defineInRange("zucchini_bread (default = 6)", 6, 0, Integer.MAX_VALUE);
		olive_tomato_salad = config.defineInRange("olive_tomato_salad (default = 5)", 5, 0, Integer.MAX_VALUE);
		candy = config.defineInRange("candy (default = 5)", 5, 0, Integer.MAX_VALUE);
		borscht = config.defineInRange("borscht (default = 6)", 6, 0, Integer.MAX_VALUE);
		squid_ink_pasta = config.defineInRange("squid_ink_pasta (default = 12)", 12, 0, Integer.MAX_VALUE);
		fish_and_chips = config.defineInRange("fish_and_chips (default = 9)", 9, 0, Integer.MAX_VALUE);
		marshmallow = config.defineInRange("marshmallow (default = 3)", 3, 0, Integer.MAX_VALUE);
		pad_thai = config.defineInRange("pad_thai (default = 18)", 18, 0, Integer.MAX_VALUE);
		potato_knish = config.defineInRange("potato_knish (default = 8)", 8, 0, Integer.MAX_VALUE);
		chicory_gratin = config.defineInRange("chicory_gratin (default = 9)", 9, 0, Integer.MAX_VALUE);
		turnip_beetroot_gratin = config.defineInRange("turnip_beetroot_gratin (default = 10)", 10, 0, Integer.MAX_VALUE);
		ice_cream_sundae = config.defineInRange("ice_cream_sundae (default = 7)", 7, 0, Integer.MAX_VALUE);
		candy_cane = config.defineInRange("candy_cane (default = 6)", 6, 0, Integer.MAX_VALUE);

	}

}
